allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// Redirect Gradle output to the Flutter project's build/ directory so that
// flutter tools can locate the APK at build/app/outputs/flutter-apk/*.
rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
